#############################################################################
# Makefile for building: libwxapp_arm64-v8a.so
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  minimal.pro
# Template: app
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /home/ivan/Android/Sdk/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
CXX           = /home/ivan/Android/Sdk/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -target aarch64-linux-android21 -fno-limit-debug-info -fPIC -fstack-protector-strong -DANDROID -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -target aarch64-linux-android21 -fno-limit-debug-info -fPIC -fstack-protector-strong -DANDROID -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/ivan/.config/env/qt/5.15.2/android/include -I/home/ivan/.config/env/qt/5.15.2/android/include/QtWidgets -I/home/ivan/.config/env/qt/5.15.2/android/include/QtGui -I/home/ivan/.config/env/qt/5.15.2/android/include/QtCore -Iarm64-v8a -I/home/ivan/.config/env/qt/5.15.2/android/mkspecs/android-clang
QMAKE         = /home/ivan/.config/env/qt/5.15.2/android/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/ivan/.config/env/qt/5.15.2/android/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/ivan/.config/env/qt/5.15.2/android/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = libwxapp_arm64-v8a.so1.0.0
DISTDIR = /workspace/obs/kiko/arm64-v8a/libwxapp_arm64-v8a.so1.0.0
LINK          = /home/ivan/Android/Sdk/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -target aarch64-linux-android21 -fno-limit-debug-info
LFLAGS        = -Wl,-soname,libwxapp_arm64-v8a.so -Wl,--build-id=sha1 -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) /home/ivan/.config/env/qt/5.15.2/android/lib/libQt5Widgets_arm64-v8a.so /home/ivan/.config/env/qt/5.15.2/android/lib/libQt5Gui_arm64-v8a.so /home/ivan/.config/env/qt/5.15.2/android/lib/libQt5Core_arm64-v8a.so -lGLESv2   -llog -lz -lm -ldl -lc
AR            = /home/ivan/Android/Sdk/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar cqs
RANLIB        = /home/ivan/Android/Sdk/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ranlib
SED           = sed
STRIP         =

####### Output directory

OBJECTS_DIR   = arm64-v8a/

####### Files

SOURCES       =
OBJECTS       =
DIST          = /home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/spec_pre.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/common/unix.conf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/common/linux.conf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/common/sanitize.conf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/common/gcc-base.conf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/common/gcc-base-unix.conf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/common/clang.conf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/qdevice.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/device_config.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/qconfig.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3danimation.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dcore.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dextras.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dinput.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dquick.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3drender.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_androidextras.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_androidextras_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_concurrent.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_core.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_core_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_gamepad.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_gui.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_gui_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_help.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_help_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_location.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_location_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_multimedia.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_network.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_network_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_nfc.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_opengl.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_positioning.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_printsupport.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_qml.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_qml_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_qmltest.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_quick.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_quick_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_repparser.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_scxml.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_sensors.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_serialport.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_sql.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_sql_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_svg.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_svg_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_testlib.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_uitools.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_webchannel.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_websockets.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_webview.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_webview_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_widgets.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_xml.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_xml_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/modules/qt_lib_zlib_private.pri \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/qt_functions.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/qt_config.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/android-clang/qmake.conf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/spec_post.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/android/spec_post.prf \
		.qmake.stash \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/exclusive_builds.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/toolchain.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/default_pre.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/android/default_pre.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/resolve_config.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/android/resolve_config.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/exclusive_builds_post.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/default_post.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/build_pass.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/android/android.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/android/android_deployment_settings.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/warn_on.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/qt.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/resources_functions.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/resources.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/moc.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/unix/opengl.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/uic.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/unix/thread.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/qmake_use.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/file_copies.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/testcase_targets.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/exceptions.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/yacc.prf \
		/home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/lex.prf \
		minimal.pro
QMAKE_TARGET  = libwxapp_arm64-v8a.so
DESTDIR       =
TARGET        = libwxapp_arm64-v8a.so


first: all
####### Build rules

libwxapp_arm64-v8a.so:  $(OBJECTS)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

qmake: FORCE
	@$(QMAKE) -o Makefile minimal.pro

qmake_all: FORCE


all: Makefile libwxapp_arm64-v8a.so

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/data/dummy.cpp $(DISTDIR)/


clean: compiler_clean
	-$(DEL_FILE) *~ core *.core


distclean: clean
	-$(DEL_FILE) $(TARGET)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

aab: apk_install_target
	/home/ivan/.config/env/qt/5.15.2/android/bin/androiddeployqt --input /workspace/obs/kiko/android-wxapp-deployment-settings.json --output /workspace/obs/kiko/android-build --aab --apk /workspace/obs/kiko/android-build/wxapp.apk

apk: apk_install_target
	/home/ivan/.config/env/qt/5.15.2/android/bin/androiddeployqt --input /workspace/obs/kiko/android-wxapp-deployment-settings.json --output /workspace/obs/kiko/android-build --apk /workspace/obs/kiko/android-build/wxapp.apk

apk_install_target: first
	$(MAKE) -f $(MAKEFILE) INSTALL_ROOT=/workspace/obs/kiko/android-build install

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: arm64-v8a/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) arm64-v8a/moc_predefs.h
arm64-v8a/moc_predefs.h: /home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/data/dummy.cpp
	/home/ivan/Android/Sdk/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -target aarch64-linux-android21 -fno-limit-debug-info -fPIC -fstack-protector-strong -DANDROID -O2 -Wall -W -dM -E -o arm64-v8a/moc_predefs.h /home/ivan/.config/env/qt/5.15.2/android/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean

####### Compile

####### Install

install_target: all FORCE
	@test -d $(INSTALL_ROOT)/libs/arm64-v8a/ || mkdir -p $(INSTALL_ROOT)/libs/arm64-v8a/
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/libs/arm64-v8a/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/libs/arm64-v8a/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/libs/arm64-v8a/


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

